config/routes.rb
Rails.application.routes.draw do
  
  get 'join_team/index'
  
  post 'join_team/joining_team'
  post 'myform' => 'join_team#parse_comments'

  get 'registration_complete/index'

  get 'payment/marketplace'

  get 'payment/index'
  post 'checkpay' => 'payment#checkpay'
  get 'consent_forms/index'

  resources :student_users
  root 'registration_home#index'
  get 'students/new'

  get 'admins/see_info'

  post 'admins/mark_paid' => 'admins#mark_paid'
  post 'admins/send_email' => 'admins#send_email'

  resources :admins do
	member do
	  put 'changelogin' => 'admins#changelogin'
          patch 'changelogin' => 'admins#changelogin'
	  get 'changelogin' => 'admins#editlogin'
	  put 'changepassword' => 'admins#changepassword'
	  patch 'changepassword' => 'admins#changepassword'
	  get 'changepassword' => 'admins#editpassword'
	end
  end

  get 'sessions/admin_new'
  get 'admin/log_out' => 'sessions#log_out'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'admin_login' => 'admins#new'
  post 'admin_login' => 'admins#create'
  delete 'admin_logout' => 'admins#destroy'

  get 'advisor/create_team' => 'advisor#create_team'
  get 'advisor/see_team'

  get 'advisor/team'

  get 'advisor/info'

  get 'sessions/new'

  resources :advisor_users
  get 'advisor/index'
  

  get 'high/index'

  get 'middle/index'

  get 'elementary/index'

  get 'registration_home/index'
  
  

  resources :posts

    

end

app/views/admins/_changeloginform.html.erb
<%= form_for( @admin, :url => changelogin_admin_path(@admin) ) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% f.hidden_field :name, :value => @admin.name %>
  <% f.hidden_field :right_sig_url, :value => @admin.right_sig_url %>
  <% f.hidden_field :mkt_place_url, :value => @admin.mkt_place_url %>
  <% f.hidden_field :phone, :value => @admin.phone %>
  <% f.hidden_field :fax, :value => @admin.fax %>
  <% f.hidden_field :password, :value => @admin.password %>
  <% f.hidden_field :password_confirmation, :value => @admin.password_confirmation %>
  <% f.hidden_field :password_digest, :value => @admin.password_digest %>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/_changepasswordform.html.erb
<%= form_for( @admin, :url => changepassword_admin_path(@admin) ) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% f.hidden_field :name, :value => @admin.name %>
  <% f.hidden_field :right_sig_url, :value => @admin.right_sig_url %>
  <% f.hidden_field :mkt_place_url, :value => @admin.mkt_place_url %>
  <% f.hidden_field :phone, :value => @admin.phone %>
  <% f.hidden_field :fax, :value => @admin.fax %>
  <% f.hidden_field :email, :value => @admin.email %>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/_contactform.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :right_sig_url %><br>
    <%= f.text_field :right_sig_url %>
  </div>
  <div class="field">
    <%= f.label :mkt_place_url %><br>
    <%= f.text_field :mkt_place_url %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>(Email)<br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/changelogin.html.erb
<% if admin_logged_in? %>

<p style="color:red"><%= notice %></p>
<h1>Change Admin Email</h1>

<%= render 'changeloginform' %>

<% end %>

app/views/admins/changepassword.html.erb
<% if admin_logged_in? %>

<p style="color:red"><%= notice %></p>
<h1>Change Admin Password</h1>

<%= render 'changepasswordform' %>

<% end %>

app/views/admins/edit.html.erb
<% if admin_logged_in? %>

<div id = "main content">
<h1>Editing Admin Contact Info</h1>

<%= render 'contactform' %>
</div>

<% end %>

app/views/admins/home.html.erb
<a href="/admins/see_info">
	Advisor & Student Information
</a>

<%= button_to "Logout", admin_log_out_path, :method => "get" %>

app/views/admins/new.html.erb
<h1>New Admin User</h1>

<%= render 'form' %>

<%= link_to 'Back', registration_home_index_path %>

app/views/admins/see_info.html.erb
<% if session[:cas_user]  %>
<% @email = session[:cas_user] + "@tamu.edu" %>
<% admin = Admin.where(:email => @email).first() %>
<% if !admin.nil? %>
<p id="notice"><%= notice %></p>

<h1>Advisor Users</h1>

<table border="1">
  <thead>
    <tr>
      <th>Username</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Team Name</th>
      <th>Team Code</th>
      <th>Pay Code</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% AdvisorUser.all.each do |advisor_user| %>
      <tr>
        <td><%= advisor_user.username %></td>
        <td><%= advisor_user.first_name %></td>
        <td><%= advisor_user.last_name %></td>
        <td><%= advisor_user.team_name %></td>
        <td><%= advisor_user.team_code %></td>
        <td><%= advisor_user.pay_code %></td>
        <td><%= link_to 'Destroy', advisor_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>Unpaid Students</h1> <%= link_to "CSV", student_users_path(format: "csv") %> | <%= link_to "Excel", student_users_path(format: "xls") %> <br></br>


<table border="1">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
	  <th>Email</th>
      <th>School Name</th>
      <th>School Level</th>
      <th>Team Code</th>
      <th>Mark Paid</th>
      <th>Send Email</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% i=1 %>
    <% StudentUser.all.each do |student| %>
      <% if (student.pay_status != "yes") %>
          <tr>
            <td><%= student.first_name %></td>
            <td><%= student.last_name %></td>
            <td><%= student.email %></td>
            <td><%= student.school_name %></td>
            <td><%= student.school_level %></td>
            <td><%= student.team_code %></td>
            <%= form_tag("mark_paid") do %>
                <%= hidden_field_tag('id', student.id) %>
                <td><%= submit_tag("Mark paid") %></td>
            <% end %>
            <%= form_tag("send_email") do %>
                <%= hidden_field_tag('id', student.id) %>
                <td><%= submit_tag("Send Email") %></td>
            <% end %>
            <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<h1>Paid Students</h1> <%= link_to "CSV", student_users_path(format: "csv") %> | <%= link_to "Excel", student_users_path(format: "xls") %> <br></br>


<table border="1">
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>School Name</th>
    <th>School Level</th>
    <th>Team Code</th>
    <th>Destroy</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% i=1 %>
  <% StudentUser.all.each do |student| %>
      <% if (student.pay_status == "yes") %>
          <tr>
            <%= hidden_field_tag('id', student.id) %>
            <td><%= student.first_name %></td>
            <td><%= student.last_name %></td>
            <td><%= student.email %></td>
            <td><%= student.school_name %></td>
            <td><%= student.school_level %></td>
            <td><%= student.team_code %></td>
            <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
  <% end %>
  </tbody>
</table>
<% end %>
<% end %>

app/views/admins/show.html.erb
<% if admin_logged_in? %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>
<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @admin.phone %>
</p>
<p>
  <strong>Right Signature URL:</strong>
  <%= @admin.right_sig_url %>
</p>
<p>
  <strong>Market Place URL:</strong>
  <%= @admin.mkt_place_url %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Change Email', changelogin_admin_path(@admin) %> |
<%= link_to 'Change Password', changepassword_admin_path(@admin) %>

<% end %>