config/routes.rb
Rails.application.routes.draw do
  
  get 'join_team/index'
  
  post 'join_team/joining_team'
  post 'myform' => 'join_team#parse_comments'

  get 'registration_complete/index'

  get 'payment/marketplace'

  get 'payment/index'
  post 'checkpay' => 'payment#checkpay'
  get 'consent_forms/index'

  resources :student_users
  root 'registration_home#index'
  get 'students/new'

  get 'admins/see_info'

  post 'admins/mark_paid' => 'admins#mark_paid'
  post 'admins/send_email' => 'admins#send_email'

  resources :admins do
	member do
	  put 'changelogin' => 'admins#changelogin'
          patch 'changelogin' => 'admins#changelogin'
	  get 'changelogin' => 'admins#editlogin'
	  put 'changepassword' => 'admins#changepassword'
	  patch 'changepassword' => 'admins#changepassword'
	  get 'changepassword' => 'admins#editpassword'
	end
  end

  get 'sessions/admin_new'
  get 'admin/log_out' => 'sessions#log_out'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'admin_login' => 'admins#new'
  post 'admin_login' => 'admins#create'
  delete 'admin_logout' => 'admins#destroy'

  get 'advisor/create_team' => 'advisor#create_team'
  get 'advisor/see_team'

  get 'advisor/team'

  get 'advisor/info'

  get 'sessions/new'

  resources :advisor_users
  get 'advisor/index'
  

  get 'high/index'

  get 'middle/index'

  get 'elementary/index'

  get 'registration_home/index'
  
  

  resources :posts

    

end

app/models/advisor_user.rb
class AdvisorUser < ActiveRecord::Base
  before_save { self.username = username.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, length: {maximum: 255}, 
  			format: { with: VALID_EMAIL_REGEX }, 
			uniqueness: { case_sensitive: false }

  validates :first_name, presence: true, length: {maximum: 60}
  validates :last_name, presence: true, length: {maximum: 60}
  validates :school_name, presence: true, length: {maximum: 60}
  validates :school_level, presence: true, #length: {maximum: 60}, 
  			inclusion: { in: %w(Elementary Middle High), message: "%{value} is not a valid school level must be Elementary, Middle, or High " }
  validates :pay_code, presence: true
  has_secure_password
  validates :password, length: { minimum: 6 }, confirmation: true
  validates_confirmation_of :password

end

app/controllers/advisor_users_controller.rb
class AdvisorUsersController < ApplicationController
  before_action :set_advisor_user, only: [:show, :edit, :update, :destroy]

  # GET /advisor_users
  # GET /advisor_users.json
  def index
    @advisor_users = AdvisorUser.all
  end

  # GET /advisor_users/1
  # GET /advisor_users/1.json
  def show
  end

  # GET /advisor_users/new
  def new
    @advisor_user = AdvisorUser.new
  end

  # GET /advisor_users/1/edit
  def edit
  end
  #Generates a random pay code and checks if it exists in the database
  def genPayCode(seed)
    num = seed.to_i + rand(1000...900000)
    retcode = 'Y' + num.to_s
    done = 0
    # Check to see if the pay_code already exists
    while(done==0)
      # Checks database for code
      if AdvisorUser.where(:pay_code => retcode).blank?	
        done = done + 1 #not in database
      else
        retcode = retcode + 1 #in database, increase and check again
      end
    end
    return retcode
  end
  
  # POST /advisor_users
  # POST /advisor_users.json
  # Creates advisor user based on the parameters and redirects to the advisor home page
  def create
    @advisor_user = AdvisorUser.new(advisor_user_params)

    # generate their paycode if they are paying for students
    @advisor_user.pay_code = genPayCode(@advisor_user.id)

    @advisor_user.usertype="advisor"

    respond_to do |format|
      if @advisor_user.save
        format.html { redirect_to @advisor_user, notice: 'Advisor user was successfully created.' }
        format.json { render :show, status: :created, location: @advisor_user }
      else
        format.html { render :new }
        format.json { render json: @advisor_user.errors, status: :unprocessable_entity }
      end
    end
  end

#Updates the advisor parameters based on the changes and throws out errors for invalid entries
  # PATCH/PUT /advisor_users/1
  # PATCH/PUT /advisor_users/1.json
  def update
    respond_to do |format|
      if @advisor_user.update(advisor_user_params)
        format.html { redirect_to @advisor_user, notice: 'Advisor user was successfully updated.' }
        format.json { render :show, status: :ok, location: @advisor_user }
      else
        format.html { render :edit }
        format.json { render json: @advisor_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advisor_users/1
  # DELETE /advisor_users/1.json
#Deletes the advisor user entry
  def destroy
    @advisor_user.destroy
    if current_user
      respond_to do |format|
        format.html { redirect_to advisor_users_url, notice: 'Advisor user was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    if admin_current_user
      respond_to do |format|
        format.html { redirect_to '/admins/see_info', notice: 'Advisor user was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advisor_user
      @advisor_user = AdvisorUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advisor_user_params
      params.require(:advisor_user).permit(:username, :password, :password_confirmation, :first_name, :last_name, :school_level, :school_name, :pay_code)
    end
end

app/helpers/advisor_users_helper.rb
module AdvisorUsersHelper
end

app/views/advisor_users/_form.html.erb
<%= form_for(@advisor_user) do |f| %>
  <% if @advisor_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advisor_user.errors.count, "error") %> prohibited this advisor_user from being saved:</h2>

      <ul>
      <% @advisor_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="advisor_user_username">Email</label>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <label for="advisor_user_password_confirmation">Re-type Password</label>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <label for="advisor_user_first_name">First Name</label>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <label for="advisor_user_last_name">Last Name</label>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :school_name %>
    <%= f.text_field :school_name %>
  </div>
  <div class="field">
    <%= f.label :school_level %>
    <%= f.select :school_level, options_for_select(%w[Elementary Middle High]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advisor_users/edit.html.erb
<div id="center_form">

<%= render 'form' %>

<% if logged_in? %>

<%= link_to 'Show', @advisor_user %>
<%= link_to 'Back', advisor_users_path %>

<% end %>

<% if admin_logged_in? %>

<%= link_to 'Back', '/admins/see_info' %>

<% end %>
</div>

app/views/advisor_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Advisor Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advisor_users.each do |advisor_user| %>
      <tr>
        <td><%= advisor_user.username %></td>
        <td><%= advisor_user.password_digest %></td>
        <td><%= advisor_user.first_name %></td>
        <td><%= advisor_user.last_name %></td>
        <td><%= link_to 'Show', advisor_user %></td>
        <td><%= link_to 'Edit', edit_advisor_user_path(advisor_user) %></td>
        <td><%= link_to 'Destroy', advisor_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advisor user', new_advisor_user_path %>

app/views/advisor_users/new.html.erb
<div style="text-align:center">
<h1>New Advisor User</h1>

<div id="center_form">

<%= render 'form' %>

</div>

<%= link_to 'Back', '/sessions/new' %>

</div>

app/views/advisor_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @advisor_user.username %>
</p>

<p>
  <strong>Team Name:</strong>
  <%= @advisor_user.team_name %>
</p>

<p>
  <strong>Team Code:</strong>
  <%= @advisor_user.team_code %>
</p>

<%= link_to 'Edit', edit_advisor_user_path(@advisor_user) %> |
<%= link_to 'Login', login_path %>